grafana:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - "grafana.DOMAIN_PLACEHOLDER"
    tls:
      - secretName: grafana-tls
        hosts:
          - "grafana.DOMAIN_PLACEHOLDER"

  grafana.ini:
    server:
      root_url: https://grafana.DOMAIN_PLACEHOLDER/
    auth.generic_oauth:
      name: Dex
      enabled: true
      client_id: kubelogin
      client_secret: OIDC_CLIENT_SECRET_PLACEHOLDER
      scopes: openid email groups
      api_url: https://dex.DOMAIN_PLACEHOLDER/userinfo
      auth_url: https://dex.DOMAIN_PLACEHOLDER/auth
      token_url: https://dex.DOMAIN_PLACEHOLDER/token
      email_attribute_path: email
